## Implementação do Algoritmo Needleman–Wunsch
Fonte: https://www.youtube.com/watch?v=um8h3P216Fk

In [ ]:
# Importa bibliotecas
import numpy as np

### Pede as sequências para o usuário

In [ ]:
sequencia1 = input("Entre com a sequência 1: ")
sequencia2 = input("Entre com a sequência 2: ")
#sequencia1 = "ATCGT"
#sequencia2 = "ACGT"
#sequencia1 = "TC"
#sequencia2 = "ATC"

Entre com a sequência 1: ATCGT
Entre com a sequência 2: ACGT


### Cria duas matrizes preenchidas com 0

In [ ]:
matriz_principal = np.zeros((len(sequencia1)+1,len(sequencia2)+1))
matriz_match_mismatch = np.zeros((len(sequencia1),len(sequencia2)))

### Pontuação para matchs, mismatches e gaps

In [ ]:
match_score = 1
mismatch_score = -1
gap_score = -2

### Preenche matriz_match_mismatch com as pontuações de match e mismatch

In [ ]:
for i in range(len(sequencia1)):
  for j in range(len(sequencia2)):
    if sequencia1[i] == sequencia2[j]:
      matriz_match_mismatch[i][j] = match_score
    else:
      matriz_match_mismatch[i][j] = mismatch_score

print(matriz_match_mismatch)

[[ 1. -1. -1. -1.]
 [-1. -1. -1.  1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1. -1.]
 [-1. -1. -1.  1.]]


### Preencher a matriz principal com o algoritmo Needleman–Wunsch

#### Passo 1: Inicialização

In [ ]:
for i in range(len(sequencia1)+1):
  matriz_principal[i][0] = i * gap_score
for j in range(len(sequencia2)+1):
  matriz_principal[0][j] = j * gap_score

In [ ]:
print(matriz_principal)

[[  0.  -2.  -4.  -6.  -8.]
 [ -2.   0.   0.   0.   0.]
 [ -4.   0.   0.   0.   0.]
 [ -6.   0.   0.   0.   0.]
 [ -8.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.]]


#### Passo 2: Preenchimento da matriz

In [ ]:
for i in range(1,len(sequencia1)+1):
  for j in range(1,len(sequencia2)+1):
    matriz_principal[i][j] = max(matriz_principal[i-1][j-1]+matriz_match_mismatch[i-1][j-1],
                                 matriz_principal[i-1][j]+gap_score,
                                 matriz_principal[i][j-1]+gap_score)

print(matriz_principal)

[[  0.  -2.  -4.  -6.  -8.]
 [ -2.   1.  -1.  -3.  -5.]
 [ -4.  -1.   0.  -2.  -2.]
 [ -6.  -3.   0.  -1.  -3.]
 [ -8.  -5.  -2.   1.  -1.]
 [-10.  -7.  -4.  -1.   2.]]


#### Passo 3: Traceback

In [ ]:
alinhado1 = ""
alinhado2 = ""

ti = len(sequencia1)
tj = len(sequencia2)

while(ti > 0 or tj > 0):
  if(ti > 0 and tj > 0 and matriz_principal[ti][tj] == matriz_principal[ti-1][tj-1] + matriz_match_mismatch[ti-1][tj-1]):
    alinhado1 = sequencia1[ti-1] + alinhado1
    alinhado2 = sequencia2[tj-1] + alinhado2
    ti = ti - 1
    tj = tj - 1
  elif(ti > 0 and matriz_principal[ti][tj] == matriz_principal[ti-1][tj] + gap_score):
    alinhado1 = sequencia1[ti-1] + alinhado1
    alinhado2 = "-" + alinhado2
    ti = ti - 1
  else:
    alinhado1 = "-" + alinhado1
    alinhado2 = sequencia2[tj-1] + alinhado2
    tj = tj - 1

In [ ]:
print(len(sequencia1))
print(len(sequencia2))

5
4


### Imprime o alinhamento global

In [ ]:
print(alinhado1)
print(alinhado2)

ATCGT
A-CGT
